### ISSUE TITLE
Support for distinguishing explicit from implicit null

### ISSUE THREAD

**Issue by ccbrown** [graphql-rust/juniper#728] opened 2020-07-29 15:52 UTC
To quote the spec:

> These two field calls are similar, but are not identical:
> 
> ```graphql
> {
>   field(arg: null)
>   field
> }
> ```
> 
> The first has explicitly provided null to the argument “arg”, while the second has implicitly not provided a value to the argument “arg”. These two forms may be interpreted differently. For example, a mutation representing deleting a field vs not altering a field, respectively.

As far as I can tell, there's no good way for a field resolver to distinguish between the two. It would be nice if there were a type that could be used to make the distinction. Maybe something like...

```rust
pub enum Nullable<T> {
    ExplicitNull,
    ImplicitNull,
    Some(T),
}
```

**Comment by LegNeato** [comment] 2020-07-29 23:55
This is a duplicate of https://github.com/graphql-rust/juniper/issues/183

**Closed by LegNeato** 2020-07-29 23:55 UTC
Labels: enhancement
