### ISSUE TITLE
Fields on interface fragment spreads don't get resolved

### ISSUE THREAD

**Issue by LucasPickering** [graphql-rust/juniper#922] opened 2021-04-27 13:35 UTC
**Describe the bug**

When resolving fields defined on an interface, if the field is defined within a fragment spread, then it is omitted from the output.

I'm happy to work on a fix for this, but will need some guidance on where to look (and whatever other tips/hints you could give me).

**To Reproduce**

Using the schema defined in `juniper/src/tests/fixtures/starwars/` (I ran the `juniper_rocket_async` example to reproduce):

### Working

A simple query returns the expected result (`id` and `name` fields are populated).

```graphql
query {
  hero {
    id
    name
  }
}
```

```json
{
  "data": {
    "hero": {
      "id": "2001",
      "name": "R2-D2"
    }
  }
}
```

### Broken

But this query, using a fragment spread on the `Character` interface, is broken (`id` and `name` fields are omitted in the response):

```graphql
{
  hero {
    ... on Character {
      id
      name
    }
  }
}
```

```json
{
  "data": {
    "hero": {}
  }
}
```

**Expected behavior**

The second query above should return the exact same output as the first query.

**Additional context**

I encountered this problem using Relay in my UI, as parts of the query being generated by Relay use this pattern. Which leads me to believe that these queries should definitely be valid.

**Comment by ArsileLuci** [comment] 2021-04-28 10:50
This is clearly a regression from `0.15.3`. I downgraded `juniper` and all related crates from `0.15.4` to `0.15.3` and it helped.

Also this bug can be reproduced with unions.

**Comment by LucasPickering** [comment] 2021-04-28 11:58
@ArsileLuci I just tried downgrading to 0.15.3 and am still seeing the issue. If this is a regression in 0.15.4 though, I'd be willing to bet it's related to this PR: https://github.com/graphql-rust/juniper/pull/907

**Comment by ArsileLuci** [comment] 2021-04-28 14:47
@LucasPickering Found the issue. As You've pointed out the problem comes partially from #907 

Bug was in typename matching, at this [two rows](https://github.com/graphql-rust/juniper/pull/907/files#diff-2aa4c3fe54fa1e05c4fd649aa1d252e3ba8fd5baab1ea5a8cf2170876df4d52aR308-R309).

`fragment.type_condition.item` is the name of interface, and it was compared with `instance.concrete_type_name(sub_exec.context(), info)` which is actually exact name of the type that implements interface.

I have a fix for this, and now preparing tests to eliminate all possibilities of this reoccurring

**Comment by LucasPickering** [comment] 2021-04-28 15:28
@ArsileLuci nice find! thank you so much for finding+fixing that, much appreciated

**Comment by tyranron** [comment] 2021-04-30 12:14
@LegNeato would you be so kind to produce a release? This regression is quite a pain-in-ass.

**Closed** 2021-04-30 12:13 UTC
Labels: regression

**Comment by nikis05** [comment] 2023-02-14 11:01
@tyranron looks like regression again. Tested in 0.15.7 - 0.15.10.

**Comment by tyranron** [comment] 2023-02-14 15:14
@nikis05 hmm... 
```bash
git checkout juniper-v0.15.11
cargo test -p juniper_tests issue_922
```
This works just fine.

Maybe the test is not good enough? Could you provide repro code?

**Comment by nikis05** [comment] 2023-02-20 10:53
@tyranron I put together a minimum reproduction https://github.com/nikis05/juniper-bug/blob/master/src/lib.rs

**Comment by tyranron** [comment] 2023-02-27 16:17
@nikis05 thanks for crafting MRE. This is a bit of a different issue there, caused by spreading interface fragment on interface (`... on Character` where `Character` is an interface, not an object). This is a known issue for juniper 0.15, and unlikely will be fixed there. However, this works OK on `master`. I advise switching to it. There shouldn't be any major breaking changes for the current `master` until it gets released, which I plan to do shortly in a near future.

**Comment by tyranron** [comment] 2023-02-27 16:18
I [covered your MRE](https://github.com/graphql-rust/juniper/commit/e569476bcc6f281ab05955ffa144ec334c1b957c) in `master` to prove that it works.
