### ISSUE TITLE
FieldResult with a unit return type panics

### ISSUE THREAD

**Issue by pyros2097** [graphql-rust/juniper#161] opened 2018-03-22 16:18 UTC
I have a mutation which returns a unit like this.
```rust
  field signup(&executor, params: user::SignUpParams) -> FieldResult<()> {
```
This causes this panic to happen,
```
thread '<unnamed>' panicked at 'resolve() must be implemented by non-object output types', /home/pyros2097/.cargo/registry/src/github.com-1ecc6299db9ec823/juniper-0.9.2/src/types/base.rs:320:13
stack backtrace:
```
So shouldn't resolve be automatically implemented for () type or something. Right now after the panic the response is an empty "" which I think is because of serde.

**Comment by LegNeato** [comment] 2018-03-23 04:46
What should unit be serialized as? An empty string? Null? I don't think it is clear

**Comment by piperRyan** [comment] 2018-03-23 18:54
Possible duplicate of #29? However, if I recall the specs correctly there is no void type. The common strategy from my experience is just have a successful field within the mutation response object.

**Comment by LegNeato** [comment] 2018-03-28 18:48
Could we do a nicer error message at compile time?

**Comment by piperRyan** [comment] 2018-04-16 19:36
I can probably take a crack at doing a compile time error for void types after finals.

**Comment by theduke** [comment] 2019-05-16 11:58
Is there a reason why we don't just remove the impl for `()`?

**Comment by theduke** [comment] 2019-05-16 12:15
@davidpdrsn @tomhoule since this will affect both of you, do you see any problems with these changes?

**Closed** 2019-05-16 14:22 UTC
