### ISSUE TITLE
Implementing fields resolver alongside struct fields

### ISSUE THREAD

**Issue by ClementNerma** [graphql-rust/juniper#1048] opened 2022-03-30 19:28 UTC
Hi there!

I'm currently using Juniper for an API project and so far the experience has been pretty great!

But I'm currently facing a problem where I need to have a `struct` with a list of public fields, as well as a few methods that would act as resolvers for the struct itself. Now, the former can be achieved like this:

```rust
#[derive(GraphQLObject)]
struct Data {
  // some fields here
}
```

While the latter can be done like this:

```rust
struct Data;

#[graphql_object]
impl Data {
  fn field_resolver() { /* some code here */
}
```

But how can I achieve _both_ at the same time? Something like:

```rust
#[derive(GraphQLObject)]
struct Data {
  // some fields here
}

#[graphql_object]
impl Data {
  fn field_resolver() { /* some code here */
}
```

doesn't work as it results in a conflicting implementation of GraphQLObject.

**Comment by tyranron** [comment] 2022-03-31 08:34
@ClementNerma you cannot achieve this anyhow not in the `juniper` 0.15, nor in the upcoming 0.16 release. We have plans to allows this, but not in the urgent agenda.

I'm closing this issue as duplicate of https://github.com/graphql-rust/juniper/discussions/1045 and https://github.com/graphql-rust/juniper/issues/646.

**Closed by tyranron** 2022-03-31 08:34 UTC
Labels: duplicate, enhancement
