### ISSUE TITLE
Consider release 0.15 on crates.io

### ISSUE THREAD

**Issue by LHY-iS-Learning** [graphql-rust/juniper#749] opened 2020-08-31 03:16 UTC
**Is your feature request related to a problem? Please describe.**
It's been 9 months since the last release of Juniper on `crates.io`. Many nice features are added in master branch, and people are using master branch as their dependency.
However the iteration is fast, and people may found their code broken due to minor issues like file/folder relocation.

**Describe the solution you'd like**
A new release version on `crates.io`.

**Describe alternatives you've considered**
Find a revision in master branch and suggest people using the revision for development.

**Comment by LegNeato** [comment] 2020-08-31 07:28
Just waiting for async interfaces to land! This is a dupe of https://github.com/graphql-rust/juniper/issues/737.

**Closed by LegNeato** 2020-08-31 07:28 UTC
Labels: enhancement
